identifiers:
- authority_index: 0
  machine_index: 0
  instance_index: 0
  public_key:
  - 59
  - 106
  - 39
  - 188
  - 206
  - 182
  - 164
  - 45
  - 98
  - 163
  - 168
  - 208
  - 42
  - 111
  - 13
  - 115
  - 101
  - 50
  - 21
  - 119
  - 29
  - 226
  - 67
  - 166
  - 58
  - 192
  - 72
  - 161
  - 139
  - 89
  - 218
  - 41
  network_address: 127.0.0.1:1500
  metrics_address: 127.0.0.1:1505
- authority_index: 1
  machine_index: 0
  instance_index: 1
  public_key:
  - 59
  - 106
  - 39
  - 188
  - 206
  - 182
  - 164
  - 45
  - 98
  - 163
  - 168
  - 208
  - 42
  - 111
  - 13
  - 115
  - 101
  - 50
  - 21
  - 119
  - 29
  - 226
  - 67
  - 166
  - 58
  - 192
  - 72
  - 161
  - 139
  - 89
  - 218
  - 41
  network_address: 127.0.0.1:1502
  metrics_address: 127.0.0.1:1507
- authority_index: 2
  machine_index: 1
  instance_index: 0
  public_key:
  - 59
  - 106
  - 39
  - 188
  - 206
  - 182
  - 164
  - 45
  - 98
  - 163
  - 168
  - 208
  - 42
  - 111
  - 13
  - 115
  - 101
  - 50
  - 21
  - 119
  - 29
  - 226
  - 67
  - 166
  - 58
  - 192
  - 72
  - 161
  - 139
  - 89
  - 218
  - 41
  network_address: 127.0.0.1:1504
  metrics_address: 127.0.0.1:1509
- authority_index: 3
  machine_index: 1
  instance_index: 1
  public_key:
  - 59
  - 106
  - 39
  - 188
  - 206
  - 182
  - 164
  - 45
  - 98
  - 163
  - 168
  - 208
  - 42
  - 111
  - 13
  - 115
  - 101
  - 50
  - 21
  - 119
  - 29
  - 226
  - 67
  - 166
  - 58
  - 192
  - 72
  - 161
  - 139
  - 89
  - 218
  - 41
  network_address: 127.0.0.1:1506
  metrics_address: 127.0.0.1:1511
parameters:
  wave_length: 3
  leader_timeout:
    secs: 2
    nanos: 0
  rounds_in_epoch: 3600000
  shutdown_grace_period:
    secs: 2
    nanos: 0
  number_of_leaders: 2
  enable_pipelining: true
  consensus_only: true
num_machines: 2
instances_per_machine: 2
